# Server Port (Reads dynamic PORT assigned by Render, defaults to 8080)
server.port=${PORT:8080}

# Clever Cloud MySQL Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://byhyeel2z3fdvep5z0ep-mysql.services.clever-cloud.com:3306/byhyeel2z3fdvep5z0ep?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ugffjailooanwqzp}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:murTBe4O5MG6eOCmY6tt}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Allowed React Frontend URL for CORS (Dynamic fallback for Vercel deployment)
app.cors.allowed-origins=${CLIENT_URL:http://localhost:5173}

# Allow larger payloads for Base64 image uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Secret Key for Registering New Admins
admin.creation.secret-key=COLLEGE_ADMIN_SECRET_2026

# Spring Mail Sender Setup for Admin Email OTP Verification
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=complaint.portal.support@gmail.com
spring.mail.password=wpwo tjdb xqau ipbk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true